name: Cloudflare API Shield Upload
description: Uploads endpoint specs to the API Shield
author: SocksTheWolf

branding:
  icon: upload-cloud
  color: orange

inputs:
  zone_id:
    description: Cloudflare Zone ID
    default: ""
    required: true
  api_token:
    description: Cloudflare API Token for managing Domain/API Gateways
    required: true
    default: ""
  file_name:
    description: The specification's file name
    default: "openapi.json"
  delete_others:
    description: Deletes other specs that match the same name as the value in `file_name`
    default: true
  skip_failed_deletes:
    description: If we fail to delete a spec, should we continue the task?
    default: true
  enable:
    description: If this new spec should be enabled automatically
    default: true

outputs:
  schema_errors:
    description: "errors while processing/parsing the openapi schema"
  schemas_deleted:
    description: "number of schemas that were deleted if enabled"

runs:
  using: node24
  main: dist/index.js
